spring:
  application:
    name: msvc-catalog
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/catalogdb
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8095

file:
  upload:
    category-images: uploaded_images/category
    product-images: uploaded_images/productimage

firebase:
  credentials: firebase-credentials.json
  storage:
    bucket: ecommerce-dad-upeu.firebasestorage.app
